import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { StructuredAppFact } from "./structuredAppFacts.js";

export interface StructuredKnowledgePublishResult {
  status: "published" | "skipped_missing_app_facts" | "skipped_no_valid_rows";
  knowledge_bank_dir: string;
  app_facts_source_path: string;
  structured_path: string;
  routing_rules_path: string;
  app_fact_count: number;
  structured_hash: string | null;
  routing_rules_hash: string | null;
}

function knowledgeBankDir(input?: string): string {
  return resolve(input ?? process.env.KNOWLEDGE_BANK_DIR ?? resolve(process.cwd(), "data", "knowledge_bank"));
}

function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

function compact(value: string | undefined): string {
  return (value ?? "").replace(/\s+/g, " ").trim();
}

function emptyToNull(value: string | undefined): string | null {
  const normalized = compact(value);
  return normalized ? normalized : null;
}

function normalizeHeader(value: string): string {
  return value
    .trim()
    .toLocaleLowerCase("tr-TR")
    .replace(/\s+/g, "_");
}

function parseMarkdownTable(markdown: string): Array<Record<string, string>> {
  const tableLines = markdown
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith("|") && line.endsWith("|"));
  if (tableLines.length < 3) return [];

  const headers = tableLines[0]
    .replace(/^\|/, "")
    .replace(/\|$/, "")
    .split("|")
    .map((part) => normalizeHeader(part));

  return tableLines
    .slice(2)
    .filter((line) => !/^\|\s*-+\s*\|/.test(line))
    .map((line) => {
      const values = line
        .replace(/^\|/, "")
        .replace(/\|$/, "")
        .split("|")
        .map((part) => part.trim());
      return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? ""]));
    });
}

function aliasesFor(row: Record<string, string>, app: string, androidName: string, iosName: string): string[] {
  const aliases = new Set<string>();
  if (androidName && androidName !== app) aliases.add(androidName);
  if (iosName && iosName !== app) aliases.add(iosName);
  const notes = compact(row.notes);
  for (const raw of notes.split(/[,;/]/)) {
    const value = compact(raw);
    if (/^[A-Z0-9 -]{2,30}$/i.test(value) && !/(active|text-only|code|agency|binding|escalate|details)/i.test(value)) {
      aliases.add(value);
    }
  }
  return Array.from(aliases);
}

export function parseStructuredAppFactsFromMarkdown(markdown: string): StructuredAppFact[] {
  return parseMarkdownTable(markdown)
    .map((row) => {
      const app = compact(row.app);
      const androidName = compact(row.android_name);
      const iosName = compact(row.ios_name);
      const status = compact(row.status);
      if (!app || !androidName || !iosName || !status) return null;
      const notes = compact(row.notes);
      const textOnly = /text-only|text only|mesaj|yazi|yaz[iı]/i.test(notes);
      const videoRequired = textOnly ? false : /kamera|video|goruntulu|görüntülü/i.test(notes) ? true : null;
      return {
        app,
        android_name: androidName,
        ios_name: iosName,
        invite_code: emptyToNull(row.invite_code),
        agency_bind_code: emptyToNull(row.agency_bind_code),
        agency_code: emptyToNull(row.agency_code),
        official_url: emptyToNull(row.official_url),
        status,
        aliases: aliasesFor(row, app, androidName, iosName),
        capabilities: {
          text_only: textOnly,
          video_required: videoRequired,
        },
      };
    })
    .filter((fact): fact is StructuredAppFact => fact !== null);
}

function buildStructuredJson(facts: StructuredAppFact[]): string {
  return `${JSON.stringify({
    version: "1.0",
    source: "generated_from_app_facts_md",
    generated_at: new Date().toISOString(),
    app_facts: facts,
  }, null, 2)}\n`;
}

function buildRoutingRules(facts: StructuredAppFact[]): string {
  const textOnly = facts.filter((fact) => fact.status && fact.capabilities.text_only);
  const rows = textOnly.length > 0
    ? textOnly.map((fact) =>
        `| Text-only, messaging-first, or camera-avoidant candidate | ${fact.app} (iPhone: ${fact.ios_name}) | ${fact.app} is marked text-only in app_facts.md; do not present camera/video as required. |`
      )
    : ["| Text-only or camera-avoidant candidate | owner_review_required | No text-only app is marked in app_facts.md; escalate instead of inventing routing. |"];

  return [
    "# App Routing Rules",
    "",
    "Generated from app_facts.md. Do not edit this file directly; update app_facts.md and run structured knowledge publish.",
    "",
    "| Candidate profile | Recommended app | Grounding |",
    "|---|---|---|",
    ...rows,
    "",
    "Routing safety:",
    "- Mention only owner-approved apps from app_facts.md.",
    "- For messaging/text-only candidates, prefer the text-only app if one is present.",
    "- Do not invent links, earnings, camera rules, account rules, or setup requirements.",
    "",
  ].join("\n");
}

export function publishStructuredKnowledgeSources(options: {
  knowledgeBankDir?: string;
} = {}): StructuredKnowledgePublishResult {
  const dir = knowledgeBankDir(options.knowledgeBankDir);
  const appFactsSourcePath = resolve(dir, "app_facts.md");
  const structuredPath = resolve(dir, "app_facts_structured.json");
  const routingRulesPath = resolve(dir, "app_routing_rules.md");

  if (!existsSync(appFactsSourcePath)) {
    return {
      status: "skipped_missing_app_facts",
      knowledge_bank_dir: dir,
      app_facts_source_path: appFactsSourcePath,
      structured_path: structuredPath,
      routing_rules_path: routingRulesPath,
      app_fact_count: 0,
      structured_hash: null,
      routing_rules_hash: null,
    };
  }

  const markdown = readFileSync(appFactsSourcePath, "utf8");
  const facts = parseStructuredAppFactsFromMarkdown(markdown);
  if (facts.length === 0) {
    return {
      status: "skipped_no_valid_rows",
      knowledge_bank_dir: dir,
      app_facts_source_path: appFactsSourcePath,
      structured_path: structuredPath,
      routing_rules_path: routingRulesPath,
      app_fact_count: 0,
      structured_hash: null,
      routing_rules_hash: null,
    };
  }

  const structuredJson = buildStructuredJson(facts);
  const routingRules = buildRoutingRules(facts);
  mkdirSync(dirname(structuredPath), { recursive: true });
  writeFileSync(structuredPath, structuredJson, "utf8");
  writeFileSync(routingRulesPath, routingRules, "utf8");

  return {
    status: "published",
    knowledge_bank_dir: dir,
    app_facts_source_path: appFactsSourcePath,
    structured_path: structuredPath,
    routing_rules_path: routingRulesPath,
    app_fact_count: facts.length,
    structured_hash: sha256(structuredJson),
    routing_rules_hash: sha256(routingRules),
  };
}
